import { NextResponse } from "next/server";

type SimulatedPRResponse = {
  success: boolean;
  mode: "simulated-pr-preview";
  message: string;
  repositoryUrl: string;
  branchName: string;
  filePath: string;
  commitMessage: string;
  prTitle: string;
  prBody: string;
  note: string;
};

type RealPRResponse = {
  success: boolean;
  mode: "real-github-pr";
  message: string;
  prUrl: string;
  branchName: string;
  filePath: string;
  commitMessage: string;
  prTitle: string;
  note: string;
};

type CreatePRResponse = SimulatedPRResponse | RealPRResponse;

// Sanitize function name for use in branch names and file paths
function sanitizeFunctionName(functionName: string): string {
  // Convert to lowercase and replace special characters with hyphens
  return functionName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, ""); // Remove leading/trailing hyphens
}

// Check if the repository URL matches the configured demo repository
function isConfiguredDemoRepo(repoUrl: string): boolean {
  const owner = process.env.GITHUB_DEMO_OWNER;
  const repo = process.env.GITHUB_DEMO_REPO;
  
  if (!owner || !repo) {
    return false;
  }
  
  const expectedUrl = `https://github.com/${owner}/${repo}`;
  return repoUrl === expectedUrl;
}

// Create a real GitHub PR using the GitHub REST API
async function createRealGitHubPR(
  testCode: string,
  functionName: string,
  repoUrl: string
): Promise<RealPRResponse> {
  const token = process.env.GITHUB_TOKEN;
  const owner = process.env.GITHUB_DEMO_OWNER;
  const repo = process.env.GITHUB_DEMO_REPO;

  if (!token || !owner || !repo) {
    throw new Error("GitHub configuration missing");
  }

  const safeFunctionName = sanitizeFunctionName(functionName);
  const timestamp = Date.now();
  const branchName = `testforge/add-tests-${safeFunctionName}-${timestamp}`;
  const filePath = `__tests__/${safeFunctionName}.test.ts`;
  const commitMessage = `test: add Jest tests for ${functionName}`;
  const prTitle = `Add tests for ${functionName}`;

  const headers = {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
  };

  // Step 1: Get repository metadata to obtain default branch
  const repoResponse = await fetch(
    `https://api.github.com/repos/${owner}/${repo}`,
    { headers }
  );

  if (!repoResponse.ok) {
    throw new Error(`Failed to fetch repository metadata: ${repoResponse.statusText}`);
  }

  const repoData = await repoResponse.json();
  const defaultBranch = repoData.default_branch;

  // Step 2: Get the base branch reference
  const refResponse = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/git/ref/heads/${defaultBranch}`,
    { headers }
  );

  if (!refResponse.ok) {
    throw new Error(`Failed to fetch base branch reference: ${refResponse.statusText}`);
  }

  const refData = await refResponse.json();
  const baseSha = refData.object.sha;

  // Step 3: Create new branch
  const createBranchResponse = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/git/refs`,
    {
      method: "POST",
      headers: {
        ...headers,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        ref: `refs/heads/${branchName}`,
        sha: baseSha,
      }),
    }
  );

  if (!createBranchResponse.ok) {
    throw new Error(`Failed to create branch: ${createBranchResponse.statusText}`);
  }

  // Step 4: Commit test file to the new branch
  const contentBase64 = Buffer.from(testCode).toString("base64");
  const commitResponse = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/contents/${filePath}`,
    {
      method: "PUT",
      headers: {
        ...headers,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        message: commitMessage,
        content: contentBase64,
        branch: branchName,
      }),
    }
  );

  if (!commitResponse.ok) {
    throw new Error(`Failed to commit file: ${commitResponse.statusText}`);
  }

  // Step 5: Create pull request
  const prBody = `This pull request adds generated Jest tests for the \`${functionName}\` function.

## Generated by TestForge Pro

This PR was automatically created by the TestForge Pro demo workflow, showcasing AI-powered test generation capabilities.

### What's included:
- Comprehensive Jest test suite for \`${functionName}\`
- Test file: \`${filePath}\`
- Branch: \`${branchName}\`

### Review notes:
- Tests were generated using AI assistance
- Please review test coverage and assertions
- Adjust test cases as needed for your specific requirements

---
*Generated with TestForge Pro - IBM Bob Hackathon Project*`;

  const prResponse = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/pulls`,
    {
      method: "POST",
      headers: {
        ...headers,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        title: prTitle,
        head: branchName,
        base: defaultBranch,
        body: prBody,
      }),
    }
  );

  if (!prResponse.ok) {
    throw new Error(`Failed to create pull request: ${prResponse.statusText}`);
  }

  const prData = await prResponse.json();

  return {
    success: true,
    mode: "real-github-pr",
    message: `Successfully created pull request #${prData.number} in ${owner}/${repo}`,
    prUrl: prData.html_url,
    branchName,
    filePath,
    commitMessage,
    prTitle,
    note: "Created only for the configured demo repository using server-side GitHub credentials.",
  };
}

// Validate if a string is a valid GitHub repository URL
function isValidGitHubUrl(url: string): boolean {
  if (!url) return false;
  const githubUrlPattern = /^https:\/\/github\.com\/[a-zA-Z0-9_-]+\/[a-zA-Z0-9_.-]+\/?$/;
  return githubUrlPattern.test(url);
}

// Generate simulated PR preview response
function generateSimulatedPRPreview(
  testCode: string,
  functionName: string,
  repoUrl: string
): SimulatedPRResponse {
  const safeFunctionName = sanitizeFunctionName(functionName);

  // Validate repoUrl and use fallback if invalid
  const validRepoUrl = isValidGitHubUrl(repoUrl)
    ? repoUrl
    : "https://github.com/NboTop/testforge-pro";

  return {
    success: true,
    mode: "simulated-pr-preview",
    message: "No real PR was created. This preview shows what would be prepared for GitHub.",
    repositoryUrl: validRepoUrl,
    branchName: `testforge/add-tests-${safeFunctionName}`,
    filePath: `__tests__/${safeFunctionName}.test.ts`,
    commitMessage: `test: add Jest tests for ${functionName}`,
    prTitle: `Add tests for ${functionName}`,
    prBody: `This simulated pull request would add generated Jest tests for the \`${functionName}\` function.\n\nIn production, this would:\n- Create a new branch from main\n- Commit the test file using authenticated GitHub API access\n- Open a pull request with the changes\n\n**Note:** Real PR creation requires GitHub authentication and write permissions.`,
    note: "No real pull request was created. Real PR creation is restricted to the configured demo repository.",
  };
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { testCode, functionName, repoUrl } = body;

    if (!testCode || !functionName) {
      return NextResponse.json(
        { error: "Test code and function name are required" },
        { status: 400 }
      );
    }

    // Use provided repoUrl or fallback to default
    const targetRepoUrl = repoUrl || "https://github.com/NboTop/testforge-pro";

    // Check if this is the configured demo repository and we have a token
    const token = process.env.GITHUB_TOKEN;
    const isDemoRepo = isConfiguredDemoRepo(targetRepoUrl);

    if (isDemoRepo && token) {
      // Attempt to create a real GitHub PR
      try {
        const realPRResponse = await createRealGitHubPR(
          testCode,
          functionName,
          targetRepoUrl
        );
        return NextResponse.json(realPRResponse);
      } catch (error) {
        // If real PR creation fails, fall back to simulation
        console.error("Real PR creation failed, falling back to simulation:", error);
        const simulatedResponse = generateSimulatedPRPreview(
          testCode,
          functionName,
          targetRepoUrl
        );
        return NextResponse.json(simulatedResponse);
      }
    } else {
      // Return simulated PR preview for all other repositories
      const simulatedResponse = generateSimulatedPRPreview(
        testCode,
        functionName,
        targetRepoUrl
      );
      return NextResponse.json(simulatedResponse);
    }
  } catch (error) {
    console.error("Error in create-pr route:", error);
    return NextResponse.json(
      { error: "Failed to create pull request" },
      { status: 500 }
    );
  }
}

// Made with Bob
